---
- name: Instalando Nginx
  apt: name=nginx state=latest

- name: Copiando index.html
  template: src=index.html dest=/usr/share/nginx/html

- name: Iniciando serviço
  systemd: name=nginx state=restarted  

...
