---
- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes

- name: Instalando pacotes essenciais
  apt:
   name:
    - vim
    - curl  
    - telnet
    - unzip
    - wget
    - net-tools
    - htop
    - nmap
   state: present
